import { test, expect } from '@playwright/test';

test('Verify Profile Editor UI', async ({ page }) => {
  await page.goto('http://localhost:5173');

  // Wait for the app to initialize
  await page.waitForTimeout(2000);

  // Open the profile view
  await page.click('#btn-show-profile');

  // Wait for the "Your Profile" header
  await expect(page.locator('#profile-view-title')).toHaveText('Your Profile');

  // Click 'Edit Bio'
  await page.click('#btn-edit-profile');

  // Ensure the editor container becomes visible
  await expect(page.locator('#profile-editor-container')).toBeVisible();

  // Type a custom bio
  await page.fill('#profile-edit-bio-input', 'This is a test bio generated by Playwright.');

  // Click 'Save'
  await page.click('#btn-save-profile');

  // Ensure the bio text updates
  await expect(page.locator('#profile-view-custom-bio')).toHaveText('This is a test bio generated by Playwright.');

  // Take a screenshot of the profile page with the updated bio
  await page.screenshot({ path: '/home/jules/verification/profile_editor.png' });
});
